sonar.projectKey=ankitsharma21598_mern-pizza-auth-service
sonar.organization=ankitsharma21598
sonar.projectName=mern-pizza-auth-service
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migration/**/*
sonar.qualitygate.wait=true # wait for the quality gate to be passed
sonar.javascript.lcov.reportPaths=./coverage/lcov.info # report the coverage
sonar.scm.exclusions.disabled=true # disable the scm exclusions